ALTER TABLE inventory
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE pick_task
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
